export const exampleQueries = [
  "Calculate the total amount of buy transactions in the past 1 hour (3.24s)",
  "Count the number of records that have not been verified for more than 5 minutes, grouped by token (9.61s)",
  "Find the top 5 tokens by total trading volume in the past 1 days (6.19s)",
  "Count the number of records that have not been verified for more than 5 minutes, grouped by token (5.89s)",
  "Query a list of the USD percentage changes for each token over the past 14 days (1.61s)",
  "List the top 3 trading days with the largest SOL volume and their tokens from pump table (4.13s)",
  "Query tokens with a trading volume of more than 100 SOL in the last 2 hours (3.70s)",
  "Query the address with the largest difference in buy/sell amount in the past hour (5.12s)",
  "Query tokens with less than 3 transactions in the last 3 days (4.80s)",
  "Query tokens with a trading volume of more than 500 SOL in the past 3 days (4.13s)",
  "Query tokens whose price fluctuations exceeded 20% in the last 12 hours (3.70s)",
  "Find all second-level records with price move over 60% in USD (2.41s)",
  "Find the 3 records with the smallest absolute difference between close and open in USD in pump table (2.91s)",
  "Find the 3 records with the smallest absolute difference between close and open in USD in pump table (2.70s)",
  "Find top 50 trader addresses by trade count in the past 24 hours (3.44s)",
  "Find tokens that had a buy amount greater than 5 SOL in the past 5 minutes (1.44s)",
  "Find addresses where total sell greater than total buy in the past 24 hours (5.16s)",
  "Find wallet addresses that interacted with at least ten different tokens in the past twenty four hours (4.58s)",
  "Query the 20 tokens with the largest transaction volume in the past hour (9.38s)",
  "Query the top 20 wallets with the highest transaction fees today and the number of transactions (3.16s)",
];
